version: '3.8'

services:
  db:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: collegehelper
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
       MYSQL_TCP_PORT: 3300
       LANG: ru_RU.UTF-8  
     volumes:
       - ./dbdata:/var/lib/mysql
     expose:
       - 3300
     ports:
       - 3300:3300

  app:
    depends_on:
    - db
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DBHOST=db
    ports:
      - 8085:8080
      - 8086:8081 

  tgBot:
    depends_on:
    - app
    build:
      context: ../college_helper_bot/
      dockerfile: Dockerfile

volumes:
  dbdata:
  mysql-initdb:
