version: '3.8'

services:
  db:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: collegehelper
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - ./dbdata:/var/lib/mysql
     expose:
       - 3306
     ports:
       - 3307:3306

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: app/Dockerfile-prod
    environment:
      - DBHOST=db
      - ASPNETCORE_Kestrel__Certificates__Default__Password=default
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    user: root
    expose:
      - 8080
    ports:
      - 8085:8080
      - 8086:8081

  tg-bot: 
    depends_on:
      - app
    build:
      context: ../college_helper_bot/
      dockerfile: Dockerfile
    stdin_open: true  
    restart: unless-stopped

volumes:
  dbdata:
  mysql-initdb:
